In [1]:
import numpy as np


In [ ]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
#print array

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
a=np.array([[1,2,3,4,5]])
print(a)
#print array

[[1 2 3 4 5]]


In [ ]:
a=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(a)
#print array 

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [ ]:
a = np.array([[1,2,3,4,5],[6,7,8,9,10]], ndmin=3)
print(a)
print("Number of dimensions:", a.ndim)
#finding the number of dimensions of an array using ndim attribute

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]]
Number of dimensions: 3


In [12]:
arr = np.array([1, 2, 3, 4])
print(arr[0])

1


In [13]:
#finding shape size of an array using shape attribute
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a.shape)
print(a.size)

(3, 3)
9


In [14]:
#reshaping an array using reshape() method
a = np.array([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]])
newa=a.reshape(4, 3)
print(newa)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [19]:
 #resizing an array using resize() method
a=np.array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])
newa=np.resize(a, ( 10))
print(newa)

[1 2 3 4 5 6 7 8 9 1]


In [20]:
#splitting an array using array_split() method
a = np.array([1, 2,3, 4, 5, 6, 7, 8])
newa = np.array_split(a, 4) 
print(newa)

[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8])]


In [22]:
#contacnation of arrays using concatenate() method
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
newx = np.concatenate((a, b), axis=0)
print(newx)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
