In [1]:
import numpy as np

In [2]:
a=np.array([[0,1],[2,3]])
b=np.resize(a,(2,3))
print(a)
print(b)

[[0 1]
 [2 3]]
[[0 1 2]
 [3 0 1]]


In [ ]:
arr=np.array([['mango'],['banana'],['grapes'],['apple']])
print(np.sort(arr,))

[['mango']
 ['banana']
 ['grapes']
 ['apple']]
[['apple']
 ['banana']
 ['grapes']
 ['mango']]


In [ ]:
list1=[1,6,3,4,5]
arr=np.array(list1)
print(np.sort(arr))

[1 3 4 5 6]


In [7]:
x=np.array([[1,2,3,4,5]],dtype=np.int8)
print(x)

[[1 2 3 4 5]]
